export const POWERUP = {
  DOUBLE_REWARD: 0,
  REVEAL_CHASERS: 1,
  TRANSFER_TASK: 2,
  DISABLE_LOCATION: 3,
  FREEZE_CHASERS: 4,
} as const;

export const PERSISTENT_POWERUPS = [POWERUP.DOUBLE_REWARD, POWERUP.TRANSFER_TASK] as const;
export const DIALOG_POWERUPS = [POWERUP.REVEAL_CHASERS, POWERUP.DISABLE_LOCATION, POWERUP.FREEZE_CHASERS] as const;
